version: "3.4"
services:
  squid:
    image: sameersbn/squid:3.5.27-2
    ports:
      - "8080:3128"
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf
      - ./config/passwords:/etc/squid/passwords
    restart: always
